# Assignment 02
The following assignment is a step-by-step process to implement a multiclass classification using Iris dataset.

**Note:**

- Please note that every question has 0.5 and it provides five out of total ten marks for the assignment. 5/10%

The video presentation 5/10%.

Without YouTube presentation you receive no mark for the submission.

In [ ]:
#00 The iris.csv file (Iris dataset) is located in the Assignment folder below the current ipynb file.

 **Important Note:** We are NOT allowed to import the dataset from Keras. We need to upload the provided iris.csv file to colab from our Google Drive.

In [ ]:
#00 1st, upload the iris.csv into your Google Drive (your Colab folder).

In [ ]:
#01-a Find the path of iris.csv file, and save it in a variable called fileName.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
fileName = "/content/drive/MyDrive/Colab Notebooks/Assignment_02_iris.csv"

In [ ]:
#01-b Read the content of the iris.csv file and save it in a variable, named iris.

In [3]:
import pandas as pd

iris = pd.read_csv(fileName)

In [ ]:
#01-c Show the first 5 rows of the dataframe.

In [4]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

As you see, the last column contains strings. We want to convert these strings to integers,  and we can work with them easily in our Neural Network model.

setosa -> 0

versicolor -> 1

virginica -> 2

In [ ]:
#2-a Convert the last column strings to integers, as
# setosa -> 0
# versicolor -> 1
# virginica -> 2

In [5]:
iris.iloc[:, -1] = iris.iloc[:, -1].map({
    "setosa": 0,
    "versicolor": 1,
    "virginica": 2
})

In [ ]:
#2-b Now, check the first 5 elements of the iris dataset once again:

In [41]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

In [ ]:
#03-a Select the first four columns of the dataframe as the Data and call the data x.

In [8]:
x = iris.iloc[:, 0:4]
x.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [ ]:
#03-b Select the last column as the label and call it y.

In [10]:
y = iris.iloc[:, -1]
y.head()

0    0
1    0
2    0
3    0
4    0
Name: species, dtype: object

In [ ]:
#04 Now, it is the time to split the data (x) and the label (y) into training and testin segments,
#   and call them parts x_train,x_test,y_train,y_test.

In [ ]:
#04-a Split the data, and label ito training and testing segments, while the size of test data is 20%,
#     and use randome_state = 123 to make all the answers similar in the whole class.

In [11]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=123
)

In [12]:
#04-b Check the first five rows of  x_train,x_test,y_train,y_test.

In [13]:
x_train.head()

     sepal_length  sepal_width  petal_length  petal_width
130           7.4          2.8           6.1          1.9
119           6.0          2.2           5.0          1.5
29            4.7          3.2           1.6          0.2
0             5.1          3.5           1.4          0.2
62            6.0          2.2           4.0          1.0

In [14]:
x_test.head()

     sepal_length  sepal_width  petal_length  petal_width
72            6.3          2.5           4.9          1.5
112           6.8          3.0           5.5          2.1
132           6.4          2.8           5.6          2.2
88            5.6          3.0           4.1          1.3
37            4.9          3.1           1.5          0.1

In [15]:
y_train.head()

130    2
119    2
29     0
0      0
62     1
Name: species, dtype: object

In [16]:
y_test.head()

72     1
112    2
132    2
88     1
37     0
Name: species, dtype: object

In [ ]:
#04-c Check the length of the x_train and x_test. If the numbers are 120 & 30, AWESOME!
#     You are good to continue!

In [17]:
len(x_train)

120

In [18]:
len(x_test)

30

In [ ]:
#05-a Convert y_train and y_test from categorical to one-hot encoded values, and call them
#     one_hot_train_labels, and one_hot_test_labels, respectively.

In [20]:
from tensorflow.keras.utils import to_categorical

one_hot_train_labels = to_categorical(y_train)
one_hot_test_labels = to_categorical(y_test)
one_hot_train_labels[:5]

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
#06-a Define a sequential model that contains 3 dense layers.
#     In the first and second layers, use 100 hidden units (neurons) and a 'relu' activation function.
#     For the last layer, we need to use 3 as the number of output,
#     and the reason is we have three classes (setosa -> 0, versicolor -> 1, virginica -> 2)
#     Also, please pick an appropriate loss function for the last layer.
#     (You may already have guessed what could be the best loss function when we have converted the categorical values to encoded values.)

In [40]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Input

model = Sequential([
    Input(shape=(x_train.shape[1],)),
    Dense(100, activation='relu'),
    Dense(100, activation='relu'),
    Dense(3, activation='softmax')
])

In [ ]:
#06-b Now, compile your model using the 'rmsprop' optimizer, an appropriate loss function, and 'accuracy' for your metrics.

In [23]:
model.compile(
    optimizer='rmsprop',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
#07-a Train your model using epoch=20, batch=10.

In [24]:
history = model.fit(
    x_train,
    one_hot_train_labels,
    epochs=20,
    batch_size=10
)

Epoch 1/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5737 - loss: 0.8803
Epoch 2/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7925 - loss: 0.6251
Epoch 3/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7829 - loss: 0.5906
Epoch 4/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8892 - loss: 0.4284
Epoch 5/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8757 - loss: 0.3520
Epoch 6/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9731 - loss: 0.3234
Epoch 7/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9525 - loss: 0.2775
Epoch 8/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9407 - loss: 0.2730
Epoch 9/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9237 - loss: 0.2518
Epoch 10/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9223 - loss: 0.2167
Epoch 11/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9633 - loss: 0.1737
Epoch 12/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9940 - loss: 0.1458
Epoch 13/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9336 - loss: 0.1606
Epoch 14/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9848 - loss: 0.1230
Epoch 15/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9727 - loss: 0.1171
Epoch 16/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9418 - loss: 0.1427
Epoch 17/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9321 - loss: 0.1392
Epoch 18/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9764 - loss: 0.1165
Epoch 19/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9804 - loss: 0.1263
Epoch 20/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9663 - loss: 0.1051

In [ ]:
#08-a Calculate the result, evaluating x_test and one_hot_test_label, and report on the accuracy of your model.

In [25]:
test_loss, test_accuracy = model.evaluate(x_test, one_hot_test_labels)
print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 244ms/step - accuracy: 0.9667 - loss: 0.1452
Test Loss: 0.1451742798089981
Test Accuracy: 0.9666666388511658

In [ ]:
#09-a Now, we repeat all we have done in #06-a with the following parameters:
#     In the first and second hidden layers, use 10 hidden units (neurons) and a 'relu' activation function.
#     For the output layer, we need to use 3.

In [26]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Input
model_10 = Sequential([
    Input(shape=(x_train.shape[1],)),
    Dense(10, activation='relu'),
    Dense(10, activation='relu'),
    Dense(3, activation='softmax')
])
model_10.compile(
    optimizer='rmsprop',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
#09-b Use the same settings as for #06-b (compile using the same optimizer, loss function) and output the accuracy

In [31]:
history_10 = model_10.fit(
    x_train,
    one_hot_train_labels,
    epochs=20,
    batch_size=10
)
test_loss_10, test_accuracy_10 = model_10.evaluate(x_test, one_hot_test_labels)
print("Test Accuracy (10 neurons, 20 epochs):", test_accuracy_10)

Epoch 1/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9444 - loss: 0.3004
Epoch 2/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9673 - loss: 0.2585
Epoch 3/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9506 - loss: 0.2747
Epoch 4/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9386 - loss: 0.2750
Epoch 5/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9404 - loss: 0.2980
Epoch 6/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9283 - loss: 0.2589
Epoch 7/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9614 - loss: 0.2418
Epoch 8/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9511 - loss: 0.2359
Epoch 9/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9673 - loss: 0.2030
Epoch 10/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9637 - loss: 0.1931
Epoch 11/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9592 - loss: 0.2091
Epoch 12/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9798 - loss: 0.1893
Epoch 13/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9548 - loss: 0.2219
Epoch 14/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9512 - loss: 0.1900
Epoch 15/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9707 - loss: 0.1649
Epoch 16/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9471 - loss: 0.1743
Epoch 17/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9672 - loss: 0.1625
Epoch 18/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9729 - loss: 0.1865
Epoch 19/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9604 - loss: 0.1352
Epoch 20/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9683 - loss: 0.1577
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9667 - loss: 0.1746
Test Accuracy (10 neurons, 20 epochs): 0.9666666388511658

In [28]:
#09-c Please fit your model using epoch=4, batch=10.

In [29]:
history_10_short = model_10.fit(
    x_train,
    one_hot_train_labels,
    epochs=4,
    batch_size=10
)

Epoch 1/4
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9599 - loss: 0.3322
Epoch 2/4
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9339 - loss: 0.3299
Epoch 3/4
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9407 - loss: 0.3323
Epoch 4/4
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9538 - loss: 0.2909

In [ ]:
#09-d Calculate the result, evaluating x_test and one_hot_test_label, and report on the accuracy of your model.

In [30]:
test_loss_10_short, test_accuracy_10_short = model_10.evaluate(
    x_test,
    one_hot_test_labels
)

print("Test Accuracy (10 neurons, 4 epochs):", test_accuracy_10_short)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 307ms/step - accuracy: 1.0000 - loss: 0.2784
Test Accuracy (10 neurons, 4 epochs): 1.0

In [ ]:
#10-a In your video submission, explain each line of your code, and the arguments you've used
# Ensure to answer the following questions at a minimum:
# 10-a-i) How the number of layers or hidden units could impact the accuracy of our model.
# 10-a-ii) Do we always suffer from overfitting?
# 10-a-iii) How can we detect overfitting?
# 10-a-iv) How can we reduce overfitting?

ANSWER:
Increasing the number of layers or neurons increases model capacity, which can improve accuracy, but if the model becomes too complex it can overfit. 
We detect overfitting when training accuracy is much higher than test accuracy, and we reduce it by simplifying the model, training for fewer epochs, or using certain techniques like dropout.

In [ ]:
#10-b
# Use different settings than the ones we chose in #09
# Change each of the following once:
#   i)   optimizer
#   ii)  number of layers
#   iii) hidden units
#   iv)  number of epochs
#   v)   batch_size
# Change one parameter at a time, and rerun the cell(s), then explain the output

In [34]:
#Baseline reference
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Input

def build_model(hidden_units=(10,10), num_hidden_layers=2):
    model = Sequential()
    model.add(Input(shape=(x_train.shape[1],)))
    # hidden layers
    for i in range(num_hidden_layers):
        model.add(Dense(hidden_units[i], activation='relu'))
    # output layer
    model.add(Dense(3, activation='softmax'))
    return model

# Baseline settings from #09
baseline_model = build_model(hidden_units=(10,10), num_hidden_layers=2)
baseline_model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
baseline_model.fit(x_train, one_hot_train_labels, epochs=20, batch_size=10, verbose=0)

baseline_loss, baseline_acc = baseline_model.evaluate(x_test, one_hot_test_labels, verbose=0)
print("BASELINE (rmsprop, 2 layers, 10 units, epochs=20, batch=10) accuracy:", baseline_acc)

BASELINE (rmsprop, 2 layers, 10 units, epochs=20, batch=10) accuracy: 0.9333333373069763

In [35]:
#10-b-i) Change optimizer
model_opt = build_model(hidden_units=(10,10), num_hidden_layers=2)
model_opt.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model_opt.fit(x_train, one_hot_train_labels, epochs=20, batch_size=10, verbose=0)

loss_opt, acc_opt = model_opt.evaluate(x_test, one_hot_test_labels, verbose=0)
print("OPTIMIZER CHANGED (adam) accuracy:", acc_opt)

OPTIMIZER CHANGED (adam) accuracy: 0.8666666746139526

In [36]:
#10-b-ii) Change number of layers
#Added 1 more hidden layer, 3 total
model_layers = build_model(hidden_units=(10,10,10), num_hidden_layers=3)
model_layers.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
model_layers.fit(x_train, one_hot_train_labels, epochs=20, batch_size=10, verbose=0)

loss_layers, acc_layers = model_layers.evaluate(x_test, one_hot_test_labels, verbose=0)
print("LAYERS CHANGED (3 hidden layers) accuracy:", acc_layers)

LAYERS CHANGED (3 hidden layers) accuracy: 0.8666666746139526

In [37]:
#10-b-iii) Change hidden units
#Change 10 -> 50 in both layer
model_units = build_model(hidden_units=(50,50), num_hidden_layers=2)
model_units.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
model_units.fit(x_train, one_hot_train_labels, epochs=20, batch_size=10, verbose=0)

loss_units, acc_units = model_units.evaluate(x_test, one_hot_test_labels, verbose=0)
print("HIDDEN UNITS CHANGED (50,50) accuracy:", acc_units)

HIDDEN UNITS CHANGED (50,50) accuracy: 0.9666666388511658

In [38]:
#10-b-iv) Change number of epochs
#Change 20 -> 40 epochs
model_epochs = build_model(hidden_units=(10,10), num_hidden_layers=2)
model_epochs.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
model_epochs.fit(x_train, one_hot_train_labels, epochs=40, batch_size=10, verbose=0)

loss_epochs, acc_epochs = model_epochs.evaluate(x_test, one_hot_test_labels, verbose=0)
print("EPOCHS CHANGED (40) accuracy:", acc_epochs)

EPOCHS CHANGED (40) accuracy: 0.5666666626930237

In [39]:
#10-b-v) Change batch_size
#Change batch_size 10 -> 20
model_batch = build_model(hidden_units=(10,10), num_hidden_layers=2)
model_batch.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
model_batch.fit(x_train, one_hot_train_labels, epochs=20, batch_size=20, verbose=0)

loss_batch, acc_batch = model_batch.evaluate(x_test, one_hot_test_labels, verbose=0)
print("BATCH SIZE CHANGED (20) accuracy:", acc_batch)

BATCH SIZE CHANGED (20) accuracy: 0.800000011920929

---
# Deliverables:
1. Submit the current ipynb file on D2L
2. Please record and upload to YouTube 3-6 minute recorded video clip (aim for 5 minutes) describing the answers to the questions above, espcially #10.

Notes:
- In your submission, YOU MUST SUBMIT A LINK TO YOUR YOUTUBE VIDEO as a TEXT SUBMISSION SECTION on your D2L submission.
- Omitting this D2L comment will result in a 0% for your total mark.